# Sakha GRPO Training Notebook

Train a hospital ward assistant using GRPO (Group Relative Policy Optimization) on the Sakha environment.

**Requirements**: GPU runtime (T4 is sufficient for 0.6B model)

**What this does**:
1. Installs Sakha environment and dependencies
2. Configures GRPO training with HF TRL
3. Runs training for N episodes
4. Plots reward curves and metrics

## 1. Setup - Install Dependencies

In [ ]:
import importlib.util, sys, os

# Idempotent setup: skip install if already available (e.g. after restart)
if importlib.util.find_spec("unsloth") is not None:
    print("Dependencies already installed. Skipping setup.")
    if os.path.exists("sakha"):
        %cd sakha
else:
    print("First run: installing dependencies...")
    !git clone -b main https://github.com/atharva-again/sakha.git
    %cd sakha
    !pip install uv -q
    !uv pip install --system -e ".[dev]"
    !uv pip install --system git+https://github.com/huggingface/transformers.git@main trl jmespath
    # Pin vllm==0.18.0 to avoid torch.compile crash in 0.19.x
    # See: https://github.com/unslothai/unsloth/issues/4841
    !uv pip install -qqq vllm==0.18.0 torchvision bitsandbytes xformers unsloth

    !uv pip install tqdm  # for interactive ux

First run: installing dependencies...
Cloning into 'sakha'...
remote: Enumerating objects: 420, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 420 (delta 10), reused 18 (delta 7), pack-reused 396 (from 1)
Receiving objects: 100% (420/420), 765.29 KiB | 2.93 MiB/s, done.
Resolving deltas: 100% (266/266), done.
/content/sakha
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 52.7 MB/s eta 0:00:00
Using Python 3.12.13 environment at: /usr
Resolved 122 packages in 1.39s
Prepared 21 packages in 324ms
Installed 21 packages in 47ms
 + aiofile==3.9.0
 + caio==0.9.25
 + coverage==7.13.5
 + cyclopts==4.11.0
 + dnspython==2.8.0
 + email-validator==2.3.0
 + exceptiongroup==1.3.1
 + fastmcp==3.2.4
 + griffelib==2.0.2
 + jsonref==1.1.0
 + jsonschema-path==0.4.5
 + openapi-pydantic==0.5.1
 + openenv-core==0.2.3
 + pathable==0.5.0
 + py-key-value-aio==0.4.4
 + pytest-cov==7.1.0
 + rich-rst==1.3.2
 + sakha==0.1.0 (from file:///content/sakha)
 + tomli==2.4.1
 + tomli-w==1.2.0
 + uncalled-for==0.3.1
Using Python 3.12.13 environment at: /usr
Resolved 77 packages in 54.61s
Prepared 5 packages in 5.49s
Uninstalled 3 packages in 339ms
Installed 5 packages in 76ms
 - datasets==4.0.0
 + datasets==4.8.4
 + jmespath==1.1.0
 - pyarrow==18.1.0
 + pyarrow==24.0.0
 - transformers==5.0.0
 + transformers==5.7.0.dev0 (from git+https://github.com/huggingface/transformers.git@c472755e79aac54d675845bff5e5c821c21260af)
 + trl==1.2.0
Using Python 3.12.13 environment at: /usr
Checked 1 package in 98ms

In [ ]:
# Optional: Mount Google Drive to cache HF models across sessions
# This saves ~5-10 min on every restart by reusing downloaded weights
try:
    from google.colab import drive
    drive.mount("/content/drive")
    import os
    os.environ["HF_HOME"] = "/content/drive/MyDrive/hf_cache"
    os.makedirs(os.environ["HF_HOME"], exist_ok=True)
    print(f"HF cache set to: {os.environ['HF_HOME']}")
except Exception:
    print("Google Drive not mounted. Models will cache in default ~/.cache/huggingface/")

Mounted at /content/drive
HF cache set to: /content/drive/MyDrive/hf_cache

## HF Token Setup

For Round 2 submission, use a T4 GPU (free Colab) for smoke tests and an A100 (HF credits) for full training.

Set your HuggingFace token in Colab secrets (left panel → 🔑) as  to access gated models.

## 2. Verify Environment

In [ ]:
import sys
sys.path.insert(0, "src")

import os
import torch
import random
import matplotlib.pyplot as plt
from pathlib import Path
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
from sakha.env import SakhaEnvironment
from sakha.models import SakhaAction, ActionType
from sakha.graders import score_easy_task, score_medium_task, score_hard_task
from sakha.grpo_training import (
    build_grpo_prompt,
    build_state_aligned_examples,
    parse_action_response_with_status,
    score_completion_action,
)
from tqdm import tqdm
import json
import gc

# Prevent vLLM from reconfiguring logging (crashes Jupyter/Colab's OutStream)
os.environ["VLLM_CONFIGURE_LOGGING"] = "0"

## 3. Configure Training

Adjust these parameters based on your GPU and time constraints:

In [ ]:

# Training configuration
MODEL = "Qwen/Qwen3-0.6B"          # Model to train (0.6B fits on T4)
TASK = "hard"                      # Task difficulty: easy | medium | hard
EPISODES = 100                       # Training examples (seed × state × policy). 200 ≈ 50 optimizer steps.
MAX_STEPS = 96                       # Max steps per episode (96 = full 8hr shift)
SEED = 42                            # Random seed for reproducibility

# Unsloth config (set USE_UNSLOTH=True for 4-bit training on T4)
USE_UNSLOTH = True                   # Use Unsloth for memory-efficient training
LOAD_IN_4BIT = True                  # 4-bit quantization (critical for T4)

# GRPO specific
NUM_GENERATIONS = 4                  # Responses per prompt
LEARNING_RATE = 1e-5                 # Learning rate
MAX_COMPLETION_LENGTH = 64           # Max tokens per completion (action call is ~5 tokens with /no_think)
MAX_SEQ_LENGTH = 2048                # Prompt + completion context for vLLM/Unsloth
EVAL_MAX_NEW_TOKENS = 32             # Plenty for one action call when thinking mode is OFF

# Checkpoint directory.
# To survive Colab session restarts, we put everything (LoRA checkpoints, eval caches,
# plot) in Google Drive when it's mounted. Override with SAKHA_OUTPUT_DIR if you want
# a different path. Falls back to ./grpo_output (ephemeral) only if no Drive is found.
def _default_output_dir() -> Path:
    env_dir = os.environ.get("SAKHA_OUTPUT_DIR")
    if env_dir:
        return Path(env_dir).expanduser()
    drive_root = Path("/content/drive/MyDrive")
    if drive_root.exists():
        return drive_root / "sakha_grpo"
    return Path("./grpo_output")


CHECKPOINT_DIR = _default_output_dir()
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

print(f"Training config:")
print(f"  Model: {MODEL}")
print(f"  Task: {TASK}")
print(f"  Episodes: {EPISODES}")
print(f"  Max steps: {MAX_STEPS}")
print(f"  Use Unsloth: {USE_UNSLOTH}")
print(f"  4-bit quant: {LOAD_IN_4BIT}")
print(f"  Checkpoint dir: {CHECKPOINT_DIR}")

def _completion_text(completion):
    if isinstance(completion, list):
        return str(completion[-1]["content"])
    return str(completion)


def _metadata_value(values, completion_idx: int, completion_count: int, default):
    """Select metadata whether TRL passes it per prompt or per generation."""
    if values is None:
        return default
    if not isinstance(values, (list, tuple)):
        return values
    if len(values) == completion_count:
        return values[completion_idx]
    if len(values) == 1:
        return values[0]
    prompt_idx = min(completion_idx // NUM_GENERATIONS, len(values) - 1)
    return values[prompt_idx]


def reward_func(prompts, completions, **kwargs):
    """State-aligned reward: parse the action, reconstruct prompt state, step once."""
    rewards = []
    completion_count = len(completions)
    for idx, completion in enumerate(completions):
        seed = int(_metadata_value(kwargs.get("seed"), idx, completion_count, SEED))
        replay_actions_json = _metadata_value(
            kwargs.get("replay_actions_json"), idx, completion_count, "[]"
        )
        rewards.append(
            score_completion_action(
                _completion_text(completion),
                task=TASK,
                seed=seed,
                replay_actions_json=str(replay_actions_json),
            )
        )
    return rewards

Training config:
  Model: Qwen/Qwen3-0.6B
  Task: hard
  Episodes: 200
  Max steps: 96
  Use Unsloth: True
  4-bit quant: True

## 5. Create Dataset and Configure GRPO

In [ ]:
def create_prompt(task: str, episode_id: int = 0):
    env = SakhaEnvironment(task=task)
    obs = env.reset(seed=SEED + episode_id)
    return build_grpo_prompt(obs, task=task, episode_id=episode_id)

# Build dataset
training_examples = build_state_aligned_examples(
    task=TASK,
    episodes=EPISODES,
    seed=SEED,
    max_steps=MAX_STEPS,
)
dataset = Dataset.from_dict(training_examples)

print(f"Dataset size: {len(dataset)} prompts")

Dataset size: 200 prompts

## 6. Pre-Training Evaluation — Base LLM

In [ ]:
# RUN THIS FIRST to avoid Unsloth monkey-patch conflict

SYSTEM_PROMPT = (
    "You are a hospital ward assistant managing patients. "
    "Available actions: review_patient(patient_id), check_vitals(patient_id), "
    "administer_medicine(patient_id), alert_doctor(patient_id), escalate(patient_id), "
    "update_chart(patient_id), prepare_discharge(patient_id), medication_round(), "
    "ward_sweep(), noop(). "
    "Return exactly one final action call. Do not explain."
)

def build_eval_prompt(obs):
    pending = obs.ward_state.pending_tasks[:5] if obs.ward_state.pending_tasks else []
    tasks_str = ", ".join(f"{t.required_action}({t.patient_id})" for t in pending) or "No pending tasks"
    return (
        f"Step {obs.ward_state.current_step}. "
        f"Patients: {len(obs.ward_state.patients)}. "
        f"Pending: {obs.pending_count}. "
        f"Tasks: {tasks_str}. "
        f"What action do you take?"
    )

def parse_action_response(response):
    action, _ = parse_action_response_with_status(response)
    return action

def save_eval_cache(results, cache_path):
    """Save evaluation results to JSON for resume across sessions."""
    with open(cache_path, "w") as f:
        json.dump(results, f, indent=2, default=str)
    print(f"💾 Eval results saved to {cache_path}")

def load_eval_cache(cache_path):
    """Load cached evaluation results if available."""
    if cache_path.exists():
        with open(cache_path, "r") as f:
            results = json.load(f)
        print(f"⚡ Loaded cached eval results from {cache_path}")
        return results
    return None

def run_llm_eval_batched(task, model, tokenizer, seeds, max_steps):
    """Vectorized evaluation: runs all seeds in parallel per step for ~5x speedup."""
    from sakha.graders import score_easy_task, score_medium_task, score_hard_task
    device = next(model.parameters()).device
    print(f"Running batched eval on device: {device} | {len(seeds)} seeds × {max_steps} steps")

    TASK_GRADERS = {"easy": score_easy_task, "medium": score_medium_task, "hard": score_hard_task}
    PATIENT_COUNTS = {"easy": 5, "medium": 8, "hard": 18}
    pc = PATIENT_COUNTS[task]
    grader = TASK_GRADERS[task]

    # Initialize all environments at once
    envs = []
    observations = []
    trajectories = []
    step_rewards_all = []
    parse_failures = []
    for seed in seeds:
        env = SakhaEnvironment(patient_count=pc, task=task)
        obs = env.reset(seed=seed)
        envs.append(env)
        observations.append(obs)
        trajectories.append([obs])
        step_rewards_all.append([])
        parse_failures.append(0)


    active_mask = [True] * len(seeds)
    pbar = tqdm(total=max_steps, desc=f"Eval {task} (batched, {len(seeds)} seeds)")

    for step in range(max_steps):
        # Collect indices of environments that are still running
        active_indices = [i for i, active in enumerate(active_mask) if active]
        if not active_indices:
            pbar.update(max_steps - step)
            break

        # Build prompts using the SAME builder as training so the model sees the
        # exact distribution it was optimized on. Mismatched train/eval prompts
        # were the main cause of the trained-vs-base regression.
        # NOTE: Qwen3 has thinking mode ON by default — without enable_thinking=False
        # the model emits <think>...</think> reasoning before every action, turning
        # a 5-token action call into 100+ tokens and making eval ~5-8x slower.
        prompt_texts = []
        for i in active_indices:
            messages = build_grpo_prompt(
                observations[i], task=task, episode_id=seeds[i]
            )
            try:
                prompt_text = tokenizer.apply_chat_template(
                    messages,
                    tokenize=False,
                    add_generation_prompt=True,
                    enable_thinking=False,
                )
            except TypeError:
                # Older tokenizers / non-Qwen templates don't accept the kwarg.
                prompt_text = tokenizer.apply_chat_template(
                    messages, tokenize=False, add_generation_prompt=True
                )
            prompt_texts.append(prompt_text)

        # Batch tokenize with left-padding
        inputs = tokenizer(
            prompt_texts, return_tensors="pt", padding=True
        ).to(device)

        # Single batched generation call
        with torch.no_grad():
            outputs = model.generate(
                **inputs, max_new_tokens=EVAL_MAX_NEW_TOKENS, do_sample=False,
                pad_token_id=tokenizer.pad_token_id,
            )

        # Parse responses and step environments
        input_lens = inputs["attention_mask"].sum(dim=1)
        newly_done = []
        for batch_idx, env_idx in enumerate(active_indices):
            input_len = input_lens[batch_idx].item()
            response = tokenizer.decode(
                outputs[batch_idx][input_len:], skip_special_tokens=True
            )
            action, parsed_ok = parse_action_response_with_status(response)
            if not parsed_ok:
                parse_failures[env_idx] += 1
            obs = envs[env_idx].step(action)
            observations[env_idx] = obs
            trajectories[env_idx].append(obs)
            step_rewards_all[env_idx].append(obs.reward)

            if obs.done:
                active_mask[env_idx] = False
                newly_done.append(env_idx)


        # Log
        active_count = sum(active_mask)
        sample_idx = active_indices[0]
        sample_action = parse_action_response(
            tokenizer.decode(outputs[0][input_lens[0].item():], skip_special_tokens=True)
        )
        pbar.set_postfix({
            "active": f"{active_count}/{len(seeds)}",
            "action": sample_action.action_type.name,
        })
        for idx in newly_done:
            pbar.write(f"  🏁 Seed {seeds[idx]} finished at step {step}")
        pbar.update(1)

    pbar.close()

    # Compute per-episode results
    episodes = []
    for i, seed in enumerate(seeds):
        grader_score = grader(trajectories[i])
        metrics = envs[i].episode_metrics
        ep = {
            "seed": seed, "grader_score": grader_score,
            "total_reward": sum(step_rewards_all[i]),
            "critical_incidents_resolved": metrics.critical_incidents_resolved,
            "critical_incidents_missed": metrics.critical_incidents_missed,
            "overdue_tasks": metrics.overdue_tasks,
            "noop_steps": metrics.noop_steps,
            "parse_failures": parse_failures[i],
            "discharges_prepared": metrics.discharges_prepared,
        }
        episodes.append(ep)
        print(
            f"  Seed {seed:3}: Reward {ep['total_reward']:6.2f} | "
            f"Grader {grader_score:.4f} | Steps {len(trajectories[i])-1} | "
            f"Parse failures {parse_failures[i]}"
        )

    def mean(key):
        return sum(e[key] for e in episodes) / len(episodes)
    return {
        "task": task, "policy": "base_llm", "episodes": episodes,
        "summary": {
            "mean_grader_score": mean("grader_score"),
            "mean_total_reward": mean("total_reward"),
            "mean_critical_incidents_resolved": mean("critical_incidents_resolved"),
            "mean_critical_incidents_missed": mean("critical_incidents_missed"),
            "mean_overdue_tasks": mean("overdue_tasks"),
            "mean_noop_steps": mean("noop_steps"),
            "mean_discharges_prepared": mean("discharges_prepared"),
        }
    }

# --- Base Eval: Check cache first, then run if needed ---
BASE_CACHE = CHECKPOINT_DIR / "base_eval_cache.json"
base_results = load_eval_cache(BASE_CACHE)

if base_results is None:
    print("Loading base Qwen3-0.6B for zero-shot evaluation...")
    base_tokenizer = AutoTokenizer.from_pretrained(
        MODEL, trust_remote_code=True, padding_side="left"
    )
    if base_tokenizer.pad_token is None:
        base_tokenizer.pad_token = base_tokenizer.eos_token

    base_model = AutoModelForCausalLM.from_pretrained(
        MODEL,
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True,
    )
    base_model.eval()

    EVAL_SEEDS = list(range(42, 52))
    base_results = run_llm_eval_batched(TASK, base_model, base_tokenizer, EVAL_SEEDS, MAX_STEPS)
    save_eval_cache(base_results, BASE_CACHE)

    # Free VRAM for training
    del base_model
    del base_tokenizer
    gc.collect()
    torch.cuda.empty_cache()
else:
    EVAL_SEEDS = list(range(42, 52))

print(f"Base LLM mean grader score: {base_results['summary']['mean_grader_score']:.4f}")

Loading base Qwen3-0.6B for zero-shot evaluation...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
`torch_dtype` is deprecated! Use `dtype` instead!
WARNING:torchao:Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.10.0+cu128).
/usr/local/lib/python3.12/dist-packages/torchao/quantization/quant_api.py:1745: SyntaxWarning: invalid escape sequence '\.'
  * regex for parameter names, must start with `re:`, e.g. `re:language\.layers\..+\.q_proj.weight`.

Running batched eval on device: cuda:0 | 10 seeds × 96 steps

Eval hard (batched, 10 seeds):   0%|          | 0/96 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Eval hard (batched, 10 seeds): 100%|██████████| 96/96 [22:59<00:00, 14.37s/it, active=0/10, action=CHECK_VITALS]

  🏁 Seed 42 finished at step 95
  🏁 Seed 43 finished at step 95
  🏁 Seed 44 finished at step 95
  🏁 Seed 45 finished at step 95
  🏁 Seed 46 finished at step 95
  🏁 Seed 47 finished at step 95
  🏁 Seed 48 finished at step 95
  🏁 Seed 49 finished at step 95
  🏁 Seed 50 finished at step 95
  🏁 Seed 51 finished at step 95
  Seed  42: Reward   1.54 | Grader 0.2986 | Steps 96 | Parse failures 16
  Seed  43: Reward  -0.39 | Grader 0.2886 | Steps 96 | Parse failures 11
  Seed  44: Reward  -2.27 | Grader 0.1574 | Steps 96 | Parse failures 19
  Seed  45: Reward  -2.04 | Grader 0.0000 | Steps 96 | Parse failures 43
  Seed  46: Reward   0.65 | Grader 0.3280 | Steps 96 | Parse failures 12
  Seed  47: Reward  -1.63 | Grader 0.0000 | Steps 96 | Parse failures 35
  Seed  48: Reward  -0.07 | Grader 0.2778 | Steps 96 | Parse failures 14
  Seed  49: Reward  -0.75 | Grader 0.2563 | Steps 96 | Parse failures 17
  Seed  50: Reward  -0.99 | Grader 0.2230 | Steps 96 | Parse failures 15
  Seed  51: Reward  -2.36 | Grader 0.0000 | Steps 96 | Parse failures 26
💾 Eval results saved to grpo_output/base_eval_cache.json
Base LLM mean grader score: 0.1830

Save the base model in the drive

# 7. Load Model with Unsloth (Optional)

In [ ]:
# Decide up front whether we'll need to actually train. If a usable checkpoint
# already exists in CHECKPOINT_DIR we skip the (expensive) Unsloth/vLLM load too,
# so a session restart doesn't redo the work and VRAM stays free for trained-eval.
#   SAKHA_FORCE_RETRAIN=1   -> train fresh
#   SAKHA_RESUME_TRAINING=1 -> continue from latest checkpoint
_pretraining_ckpts = sorted(CHECKPOINT_DIR.glob("checkpoint-*"))
_force_retrain = os.environ.get("SAKHA_FORCE_RETRAIN") == "1"
_resume_training = os.environ.get("SAKHA_RESUME_TRAINING") == "1"
_will_train = (not _pretraining_ckpts) or _force_retrain or _resume_training

if _will_train and USE_UNSLOTH:
    from unsloth import FastLanguageModel, PatchFastRL
    PatchFastRL("GRPO", FastLanguageModel)

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=MODEL,
        max_seq_length=MAX_SEQ_LENGTH,
        load_in_4bit=LOAD_IN_4BIT,
        fast_inference=True,
        gpu_memory_utilization=0.6,
    )

    model = FastLanguageModel.get_peft_model(
        model,
        r=16,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_alpha=32,
        use_gradient_checkpointing="unsloth",
        random_state=SEED,
    )
    print(f"Unsloth model loaded for training: {MODEL}")
elif _will_train:
    model = MODEL
    tokenizer = None
else:
    print(
        f"Found {len(_pretraining_ckpts)} existing checkpoint(s) in {CHECKPOINT_DIR}. "
        "Skipping Unsloth load (will resume to trained-eval)."
    )
    model = None
    tokenizer = None

/tmp/ipykernel_1135/1051103320.py:2: UserWarning: WARNING: Unsloth should be imported before [transformers] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from unsloth import FastLanguageModel, PatchFastRL

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: UnslothBCOTrainer is already patched.
Unsloth: UnslothCPOTrainer is already patched.
Unsloth: UnslothDPOTrainer is already patched.
Unsloth: UnslothGKDTrainer is already patched.
Unsloth: UnslothGRPOTrainer is already patched.
Unsloth: UnslothKTOTrainer is already patched.
Unsloth: UnslothNashMDTrainer is already patched.
Unsloth: UnslothOnlineDPOTrainer is already patched.
Unsloth: UnslothORPOTrainer is already patched.
Unsloth: UnslothPPOTrainer is already patched.
Unsloth: UnslothPRMTrainer is already patched.
Unsloth: UnslothRewardTrainer is already patched.
Unsloth: UnslothRLOOTrainer is already patched.
Unsloth: UnslothSFTTrainer is already patched.
Unsloth: UnslothXPOTrainer is already patched.

WARNING:unsloth_zoo.log:Unsloth: Switching from Unsloth dynamic quant to normal quant since
we do not yet support fast inference for unsloth/qwen3-0.6b-unsloth-bnb-4bit

==((====))==  Unsloth 2026.4.8: Fast Qwen3 patching. Transformers: 4.57.6. vLLM: 0.18.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

WARNING:vllm.envs:Unknown vLLM environment variable detected: VLLM_ATTENTION_BACKEND

Unsloth: vLLM loading unsloth/qwen3-0.6b-bnb-4bit with actual GPU utilization = 69.18%
Unsloth: Your GPU has CUDA compute capability 7.5 with VRAM = 14.56 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 512. Num Sequences = 48.
Unsloth: vLLM's KV Cache can use up to 9.36 GB. Also swap space = 0 GB.
Unsloth: Not an error, but `level` is not supported in vLLM.config.CompilationConfig. Skipping.
Unsloth: Not an error, but `use_cudagraph` is not supported in vLLM.config.CompilationConfig. Skipping.
Unsloth: Not an error, but `use_inductor` is not supported in vLLM.config.CompilationConfig. Skipping.
Unsloth: Not an error, but `swap_space` is not supported in vLLM. Skipping.
Unsloth: Not an error, but `device` is not supported in vLLM. Skipping.

WARNING:vllm.engine.arg_utils:The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
WARNING:vllm.config.model:Casting torch.bfloat16 to torch.float16.

Unsloth: vLLM Bitsandbytes config using kwargs = {'load_in_8bit': False, 'load_in_4bit': True, 'bnb_4bit_compute_dtype': 'float16', 'bnb_4bit_quant_storage': 'uint8', 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': True, 'llm_int8_enable_fp32_cpu_offload': False, 'llm_int8_has_fp16_weight': False, 'llm_int8_skip_modules': ['lm_head', 'multi_modal_projector', 'merger', 'modality_projection'], 'llm_int8_threshold': 6.0}

ERROR:vllm.v1.attention.backends.fa_utils:Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
<frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
<frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:03<00:00,  1.66it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 246.43it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 3/3 [00:00<00:00,  9.84it/s, triton_per_fused__to_copy_add_mean_mul_pow_rsqrt_2]
WARNING:vllm.lora.ops.triton_ops.utils:Using default LoRA kernel configs
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 30/30 [00:52<00:00,  1.75s/it]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 18/18 [00:05<00:00,  3.21it/s]

Unsloth: Just some info: will skip parsing ['pre_feedforward_layernorm', 'post_feedforward_layernorm', 'norm', 'layer_norm2', 'ffn_norm', 'attention_norm', 'q_norm', 'layer_norm1', 'input_layernorm', 'post_attention_layernorm', 'post_layernorm', 'norm2', 'norm1', 'k_norm']

Some weights of Qwen3ForCausalLM were not initialized from the model checkpoint at unsloth/qwen3-0.6b-bnb-4bit and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Performing substitution for additional_keys=set()
Unsloth: Just some info: will skip parsing ['cross_attn_post_attention_layernorm', 'pre_feedforward_layernorm', 'post_feedforward_layernorm', 'norm', 'layer_norm2', 'ffn_norm', 'attention_norm', 'q_norm', 'layer_norm1', 'cross_attn_input_layernorm', 'input_layernorm', 'post_attention_layernorm', 'post_layernorm', 'norm2', 'norm1', 'k_norm']

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

unsloth/qwen3-0.6b-bnb-4bit does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.

Unsloth 2026.4.8 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

Unsloth model loaded for training: Qwen/Qwen3-0.6B

# 8. Configure GRPO

In [ ]:
from trl import GRPOConfig, GRPOTrainer

grpo_config = GRPOConfig(
    num_train_epochs=1,
    num_generations=NUM_GENERATIONS,
    max_completion_length=MAX_COMPLETION_LENGTH,
    learning_rate=LEARNING_RATE,
    logging_steps=1,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=2,
    save_strategy="steps",
    save_steps=50,
    save_total_limit=3,
    report_to=[],
    output_dir=str(CHECKPOINT_DIR),
    overwrite_output_dir=False,
    seed=SEED,
    remove_unused_columns=False,
    use_vllm=USE_UNSLOTH,
    vllm_gpu_memory_utilization=0.3 if USE_UNSLOTH else None,
)

# 9. Trainer Setup & Training

In [ ]:
trainer_kwargs = {
    "train_dataset": dataset,
    "reward_funcs": reward_func,
    "args": grpo_config,
}

if USE_UNSLOTH:
    trainer_kwargs["model"] = model
    trainer_kwargs["processing_class"] = tokenizer
else:
    trainer_kwargs["model"] = MODEL

# --- Training control flow ---
# Default: if checkpoints already exist in CHECKPOINT_DIR, skip training entirely
# and jump to the trained-eval cell below. Override with the env vars described
# in the Unsloth-load cell (SAKHA_FORCE_RETRAIN / SAKHA_RESUME_TRAINING).
if not _will_train:
    print(
        f"Skipping training — using existing checkpoints in {CHECKPOINT_DIR}. "
        "Set SAKHA_FORCE_RETRAIN=1 or SAKHA_RESUME_TRAINING=1 to override."
    )
else:
    trainer = GRPOTrainer(**trainer_kwargs)
    resume_path = (
        str(_pretraining_ckpts[-1])
        if (_pretraining_ckpts and _resume_training)
        else None
    )
    if resume_path:
        print(f"Resuming training from {resume_path}")
    else:
        print(f"Starting training: {EPISODES} episodes, task={TASK}")
    trainer.train(resume_from_checkpoint=resume_path)

Starting training: 200 episodes, task=hard

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 200 | Num Epochs = 1 | Total steps = 200
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 2 x 1) = 4
 "-____-"     Trainable parameters = 10,092,544 of 606,142,464 (1.67% trained)
WARNING:vllm.v1.engine.input_processor:vLLM has deprecated support for supporting different tokenizers for different LoRAs. By default, vLLM uses base model's tokenizer. If you are using a LoRA with its own tokenizer, consider specifying `--tokenizer [lora_path]` to use the LoRA tokenizer.

Unsloth: Will smartly offload gradients to save VRAM!

# 10. Post-Training Evaluation — Trained LLM

In [ ]:
TRAINED_CACHE = CHECKPOINT_DIR / "trained_eval_cache.json"
trained_results = load_eval_cache(TRAINED_CACHE)

if trained_results is None:
    ckpts = sorted(CHECKPOINT_DIR.glob("checkpoint-*"))
    if not ckpts:
        print("No checkpoints found. Skipping trained eval.")
        trained_results = None
    else:
        CHECKPOINT_PATH = str(ckpts[-1])
        print(f"Loading trained checkpoint: {CHECKPOINT_PATH}")

        # Free training-time resources before loading the eval model so we don't
        # OOM (Unsloth+vLLM hold a lot of VRAM after train()).
        try:
            del trainer
        except NameError:
            pass
        try:
            del model
        except NameError:
            pass
        gc.collect()
        torch.cuda.empty_cache()

        # Always evaluate via plain transformers + PEFT so the trained-vs-base
        # comparison is apples-to-apples (same inference framework as base eval)
        # and we don't surface the misleading "lm_head.weight ... newly
        # initialized" warning that the Unsloth/vLLM path emits for tied-
        # embedding models like Qwen3.
        from peft import PeftModel
        trained_tokenizer = AutoTokenizer.from_pretrained(
            MODEL, trust_remote_code=True, padding_side="left"
        )
        base_for_trained = AutoModelForCausalLM.from_pretrained(
            MODEL,
            torch_dtype=torch.float16,
            device_map="auto",
            trust_remote_code=True,
        )
        trained_model = PeftModel.from_pretrained(base_for_trained, CHECKPOINT_PATH)
        trained_model = trained_model.merge_and_unload()
        trained_model.eval()

        if trained_tokenizer.pad_token is None:
            trained_tokenizer.pad_token = trained_tokenizer.eos_token

        print("Running evaluation on trained model...")
        trained_results = run_llm_eval_batched(TASK, trained_model, trained_tokenizer, EVAL_SEEDS, MAX_STEPS)
        trained_results["policy"] = "trained_llm"
        save_eval_cache(trained_results, TRAINED_CACHE)
        print(f"Trained mean grader score: {trained_results['summary']['mean_grader_score']:.4f}")

        del trained_model
        del base_for_trained
        del trained_tokenizer
        gc.collect()
        torch.cuda.empty_cache()

Loading trained checkpoint: grpo_output/checkpoint-200
INFO 04-25 21:42:03 [vllm_utils.py:724] Unsloth: Patching vLLM v1 graph capture
==((====))==  Unsloth 2026.4.8: Fast Qwen3 patching. Transformers: 4.57.6. vLLM: 0.18.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: vLLM loading unsloth/qwen3-0.6b-bnb-4bit with actual GPU utilization = 59.3%
Unsloth: Your GPU has CUDA compute capability 7.5 with VRAM = 14.56 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 2048. Num Sequences = 32.
Unsloth: vLLM's KV Cache can use up to 7.93 GB. Also swap space = 0 GB.
Unsloth: Not an error, but `level` is not supported in vLLM.config.CompilationConfig. Skipping.
Unsloth: Not an error, but `use_cudagraph` is not supported in vLLM.config.CompilationConfig. Skipping.
Unsloth: Not an error, but `use_inductor` is not supported in vLLM.config.CompilationConfig. Skipping.
Unsloth: Not an error, but `swap_space` is not supported in vLLM. Skipping.
Unsloth: Not an error, but `device` is not supported in vLLM. Skipping.
INFO 04-25 21:42:08 [utils.py:233] non-default args: {'load_format': 'bitsandbytes', 'dtype': torch.float16, 'max_model_len': 2048, 'enable_prefix_caching': True, 'disable_cascade_attn': False, 'gpu_memory_utilization': 0.5930445132709982, 'max_num_batched_tokens': 4096, 'max_num_seqs': 32, 'max_logprobs': 0, 'disable_log_stats': True, 'quantization': 'bitsandbytes', 'enable_lora': True, 'max_lora_rank': 64, 'enable_chunked_prefill': True, 'compilation_config': {'mode': None, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': [], 'splitting_ops': None, 'compile_mm_encoder': False, 'compile_sizes': None, 'compile_ranges_endpoints': None, 'inductor_compile_config': {'epilogue_fusion': True, 'max_autotune': False, 'shape_padding': True, 'trace.enabled': False, 'triton.cudagraphs': False, 'debug': False, 'dce': True, 'memory_planning': True, 'coordinate_descent_tuning': False, 'trace.graph_diagram': False, 'compile_threads': 4, 'group_fusion': True, 'disable_progress': False, 'verbose_progress': True, 'triton.multi_kernel': 0, 'triton.use_block_ptr': True, 'triton.enable_persistent_tma_matmul': True, 'triton.autotune_at_compile_time': False, 'triton.cooperative_reductions': False, 'cuda.compile_opt_level': '-O2', 'cuda.enable_cuda_lto': True, 'combo_kernels': False, 'benchmark_combo_kernel': True, 'combo_kernel_foreach_dynamic_shapes': True, 'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': None, 'pass_config': {}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': None, 'static_all_moe_layers': []}, 'model': 'unsloth/qwen3-0.6b-bnb-4bit'}
WARNING 04-25 21:42:08 [envs.py:1717] Unknown vLLM environment variable detected: VLLM_ATTENTION_BACKEND
WARNING 04-25 21:42:08 [arg_utils.py:1352] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 04-25 21:42:09 [model.py:533] Resolved architecture: Qwen3ForCausalLM
WARNING 04-25 21:42:09 [model.py:1920] Casting torch.bfloat16 to torch.float16.
INFO 04-25 21:42:09 [model.py:1582] Using max model len 2048
INFO 04-25 21:42:10 [scheduler.py:231] Chunked prefill is enabled with max_num_batched_tokens=4096.
Unsloth: vLLM Bitsandbytes config using kwargs = {'load_in_8bit': False, 'load_in_4bit': True, 'bnb_4bit_compute_dtype': 'float16', 'bnb_4bit_quant_storage': 'uint8', 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': True, 'llm_int8_enable_fp32_cpu_offload': False, 'llm_int8_has_fp16_weight': False, 'llm_int8_skip_modules': ['lm_head', 'multi_modal_projector', 'merger', 'modality_projection'], 'llm_int8_threshold': 6.0}
INFO 04-25 21:42:10 [vllm.py:754] Asynchronous scheduling is enabled.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/237 [00:00<?, ?B/s]

INFO 04-25 21:42:13 [core.py:103] Initializing a V1 LLM engine (v0.18.0) with config: model='unsloth/qwen3-0.6b-bnb-4bit', speculative_config=None, tokenizer='unsloth/qwen3-0.6b-bnb-4bit', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=unsloth/qwen3-0.6b-bnb-4bit, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_endpoints': [4096], 'inductor_compile_config': {'epilogue_fusion': True, 'max_autotune': False, 'shape_padding': True, 'trace.enabled': False, 'triton.cudagraphs': False, 'debug': False, 'dce': True, 'memory_planning': True, 'coordinate_descent_tuning': False, 'trace.graph_diagram': False, 'compile_threads': 4, 'group_fusion': True, 'disable_progress': False, 'verbose_progress': True, 'triton.multi_kernel': 0, 'triton.use_block_ptr': True, 'triton.enable_persistent_tma_matmul': True, 'triton.autotune_at_compile_time': False, 'triton.cooperative_reductions': False, 'cuda.compile_opt_level': '-O2', 'cuda.enable_cuda_lto': True, 'combo_kernels': False, 'benchmark_combo_kernel': True, 'combo_kernel_foreach_dynamic_shapes': True, 'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 64, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
INFO 04-25 21:42:13 [parallel_state.py:1395] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:59365 backend=nccl
INFO 04-25 21:42:13 [parallel_state.py:1717] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 04-25 21:42:17 [topk_topp_sampler.py:51] Using FlashInfer for top-p & top-k sampling.
INFO 04-25 21:42:17 [gpu_model_runner.py:4481] Starting to load model unsloth/qwen3-0.6b-bnb-4bit...
ERROR 04-25 21:42:18 [fa_utils.py:145] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
INFO 04-25 21:42:18 [cuda.py:317] Using FLASHINFER attention backend out of potential backends: ['FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 04-25 21:42:18 [bitsandbytes_loader.py:786] Loading weights with BitsAndBytes quantization. May take a while ...

<frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
<frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.

model.safetensors:   0%|          | 0.00/539M [00:00<?, ?B/s]

INFO 04-25 21:42:34 [weight_utils.py:574] Time spent downloading weights for unsloth/qwen3-0.6b-bnb-4bit: 15.486702 seconds
INFO 04-25 21:42:34 [weight_utils.py:618] No model.safetensors.index.json found in remote.

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

INFO 04-25 21:42:35 [punica_selector.py:20] Using PunicaWrapperGPU.
INFO 04-25 21:42:37 [gpu_model_runner.py:4566] Model loading took 0.64 GiB memory and 17.782534 seconds
INFO 04-25 21:42:52 [backends.py:988] Using cache directory: /root/.cache/vllm/torch_compile_cache/722aa9b7c9/rank_0_0/backbone for vLLM's torch.compile
INFO 04-25 21:42:52 [backends.py:1048] Dynamo bytecode transform time: 14.04 s

Unsloth: Compiling kernels: 0it [00:00, ?it/s]

INFO 04-25 21:42:53 [backends.py:371] Cache the graph of compile range (1, 4096) for later use

Unsloth: Compiling kernels: 0it [00:00, ?it/s]
Unsloth: Compiling kernels: 0it [00:00, ?it/s]

INFO 04-25 21:42:57 [backends.py:387] Compiling a graph for compile range (1, 4096) takes 4.57 s

INFO 04-25 21:43:04 [decorators.py:627] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/0815cf1ae695a3776216a1dd2d7bffa3506ae6e289c9964ef46a89d846104a3a/rank_0_0/model
INFO 04-25 21:43:04 [monitor.py:48] torch.compile took 26.25 s in total
INFO 04-25 21:43:05 [monitor.py:76] Initial profiling/warmup run took 0.20 s
INFO 04-25 21:43:06 [kv_cache_utils.py:826] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=64
INFO 04-25 21:43:06 [gpu_model_runner.py:5607] Profiling CUDA graph memory: PIECEWISE=22 (largest=64), FULL=14 (largest=32)
WARNING 04-25 21:43:07 [utils.py:268] Using default LoRA kernel configs
INFO 04-25 21:43:10 [gpu_model_runner.py:5686] Estimated CUDA graph memory: 0.82 GiB total
INFO 04-25 21:43:11 [gpu_worker.py:456] Available KV cache memory: 7.69 GiB
INFO 04-25 21:43:11 [gpu_worker.py:490] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.5930 to 0.6491 to maintain the same effective KV cache size.
INFO 04-25 21:43:11 [kv_cache_utils.py:1316] GPU KV cache size: 71,984 tokens
INFO 04-25 21:43:11 [kv_cache_utils.py:1321] Maximum concurrency for 2,048 tokens per request: 35.15x
INFO 04-25 21:43:11 [kernel_warmup.py:69] Warming up FlashInfer attention.
INFO 04-25 21:43:11 [vllm_utils.py:729] Unsloth: Running patched vLLM v1 `capture_model`.

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 22/22 [00:05<00:00,  3.68it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 14/14 [00:04<00:00,  3.32it/s]

INFO 04-25 21:43:21 [gpu_model_runner.py:5746] Graph capturing finished in 10 secs, took 0.48 GiB
INFO 04-25 21:43:21 [vllm_utils.py:736] Unsloth: Patched vLLM v1 graph capture finished in 10 secs.

INFO 04-25 21:43:23 [gpu_worker.py:617] CUDA graph pool memory: 0.48 GiB (actual), 0.82 GiB (estimated), difference: 0.33 GiB (68.5%).
INFO 04-25 21:43:23 [core.py:281] init engine (profile, create kv cache, warmup model) took 45.72 seconds
INFO 04-25 21:43:25 [llm.py:391] Supported tasks: ('generate',)
Unsloth: Just some info: will skip parsing ['k_norm', 'q_norm', 'post_layernorm', 'norm2', 'ffn_norm', 'input_layernorm', 'norm', 'attention_norm', 'layer_norm2', 'norm1', 'post_feedforward_layernorm', 'pre_feedforward_layernorm', 'layer_norm1', 'post_attention_layernorm']

Some weights of Qwen3ForCausalLM were not initialized from the model checkpoint at unsloth/qwen3-0.6b-bnb-4bit and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Performing substitution for additional_keys=set()
Unsloth: Just some info: will skip parsing ['k_norm', 'cross_attn_input_layernorm', 'q_norm', 'post_layernorm', 'norm2', 'ffn_norm', 'input_layernorm', 'norm', 'attention_norm', 'layer_norm2', 'norm1', 'post_feedforward_layernorm', 'pre_feedforward_layernorm', 'cross_attn_post_attention_layernorm', 'layer_norm1', 'post_attention_layernorm']

Unsloth 2026.4.8 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

Running evaluation on trained model...
Running batched eval on device: cuda:0 | 10 seeds × 96 steps

Eval hard (batched, 10 seeds): 100%|██████████| 96/96 [10:07<00:00,  6.32s/it, active=0/10, action=NOOP]

  🏁 Seed 42 finished at step 95
  🏁 Seed 43 finished at step 95
  🏁 Seed 44 finished at step 95
  🏁 Seed 45 finished at step 95
  🏁 Seed 46 finished at step 95
  🏁 Seed 47 finished at step 95
  🏁 Seed 48 finished at step 95
  🏁 Seed 49 finished at step 95
  🏁 Seed 50 finished at step 95
  🏁 Seed 51 finished at step 95
  Seed  42: Reward  -2.86 | Grader 0.0000 | Steps 96
  Seed  43: Reward  -0.73 | Grader 0.2320 | Steps 96
  Seed  44: Reward  -0.69 | Grader 0.2359 | Steps 96
  Seed  45: Reward  -2.32 | Grader 0.0000 | Steps 96
  Seed  46: Reward  -0.29 | Grader 0.2453 | Steps 96
  Seed  47: Reward  -1.07 | Grader 0.2287 | Steps 96
  Seed  48: Reward  -1.32 | Grader 0.1215 | Steps 96
  Seed  49: Reward  -0.95 | Grader 0.2360 | Steps 96
  Seed  50: Reward  -2.46 | Grader 0.0000 | Steps 96
  Seed  51: Reward  -1.53 | Grader 0.0000 | Steps 96
💾 Eval results saved to grpo_output/trained_eval_cache.json
Trained mean grader score: 0.1299

## 11. Base vs Trained Comparison

Side-by-side metrics and bar chart.

In [ ]:
if trained_results is not None:
    b = base_results["summary"]
    t = trained_results["summary"]

    print("\n## Base LLM vs Trained LLM Comparison\n")
    print("| Metric | Base LLM | Trained | Delta |")
    print("|--------|----------|---------|-------|")
    print(f"| Grader Score | {b['mean_grader_score']:.4f} | {t['mean_grader_score']:.4f} | {t['mean_grader_score'] - b['mean_grader_score']:+.4f} |")
    print(f"| Total Reward | {b['mean_total_reward']:.4f} | {t['mean_total_reward']:.4f} | {t['mean_total_reward'] - b['mean_total_reward']:+.4f} |")
    print(f"| Critical Resolved | {b['mean_critical_incidents_resolved']:.2f} | {t['mean_critical_incidents_resolved']:.2f} | {t['mean_critical_incidents_resolved'] - b['mean_critical_incidents_resolved']:+.2f} |")
    print(f"| Critical Missed | {b['mean_critical_incidents_missed']:.2f} | {t['mean_critical_incidents_missed']:.2f} | {t['mean_critical_incidents_missed'] - b['mean_critical_incidents_missed']:+.2f} |")
    print(f"| Overdue Tasks | {b['mean_overdue_tasks']:.2f} | {t['mean_overdue_tasks']:.2f} | {t['mean_overdue_tasks'] - b['mean_overdue_tasks']:+.2f} |")
    print(f"| NOOP Steps | {b['mean_noop_steps']:.2f} | {t['mean_noop_steps']:.2f} | {t['mean_noop_steps'] - b['mean_noop_steps']:+.2f} |")

    # Bar chart
    fig, ax = plt.subplots(figsize=(10, 5))
    metrics = ["Grader Score", "Total Reward", "Critical Resolved", "Overdue Tasks"]
    base_vals = [b['mean_grader_score'], b['mean_total_reward'], b['mean_critical_incidents_resolved'], b['mean_overdue_tasks']]
    trained_vals = [t['mean_grader_score'], t['mean_total_reward'], t['mean_critical_incidents_resolved'], t['mean_overdue_tasks']]
    x = range(len(metrics))
    width = 0.35
    ax.bar([i - width/2 for i in x], base_vals, width, label='Base LLM', color='#e74c3c')
    ax.bar([i + width/2 for i in x], trained_vals, width, label='Trained LLM', color='#2ecc71')
    ax.set_ylabel('Value')
    ax.set_title('Base vs Trained LLM Performance')
    ax.set_xticks(x)
    ax.set_xticklabels(metrics)
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plot_path = CHECKPOINT_DIR / "base_vs_trained.png"
    plt.savefig(plot_path, dpi=150)
    print(f"Plot saved to {plot_path}")
else:
    print("Skipping comparison — no trained eval results available.")

NameError: name 'trained_results' is not defined

## 13. Download Results

In [ ]:
# Zip results for download. CHECKPOINT_DIR may live on Drive
# (e.g. /content/drive/MyDrive/sakha_grpo) — zip it from wherever it is.
import shutil
zip_base = "grpo_results"
zip_path = shutil.make_archive(zip_base, "zip", root_dir=str(CHECKPOINT_DIR))
print(f"Archived {CHECKPOINT_DIR} → {zip_path}")

try:
    from google.colab import files
    files.download(zip_path)
except Exception:
    print("(Skip download — not in Colab)")

---

## Summary

This notebook demonstrated GRPO training on the Sakha hospital ward environment.

**Key takeaways**:
- Sakha provides a realistic hospital workflow simulation with 96-step episodes
- GRPO with Unsloth 4-bit training fits on a free Colab T4 GPU
- Compare base LLM vs trained LLM on identical seeds to measure RL improvement
- Small models (0.6B) can learn basic patterns, but larger models (4B+) show better reasoning

**Next steps**:
- Try larger models (Qwen3-4B) for better performance
- Increase episodes to 500+ for meaningful convergence
- Add eval split to track generalization
- Experiment with different reward shaping